use_frameworks!

platform :ios, '10.0'

target 'CJVideoPlayerDemo_Example' do
  pod 'CJVideoPlayerDemo', :path => '../'

  target 'CJVideoPlayerDemo_Tests' do
    inherit! :search_paths

    
  end
end
